# Generated by Django 5.2.8 on 2025-12-02 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono (nombre de Lucide)')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Color de la categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Foro',
                'verbose_name_plural': 'Categorías de Foro',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fijado')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('views_count', models.IntegerField(default=0, verbose_name='Número de Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.forumcategory', verbose_name='Categoría')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.forumpost', verbose_name='Post Padre (si es respuesta)')),
            ],
            options={
                'verbose_name': 'Post de Foro',
                'verbose_name_plural': 'Posts de Foro',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
