# Generated by Django 5.2.8 on 2025-12-02 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_forumcategory_forumpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_posts/%Y/%m/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que dieron like'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Número de Likes'),
        ),
    ]
