# Generated by Django 5.2.8 on 2025-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_image_and_likes_to_forum_post'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydocument',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='library_documents', to='auth.group', verbose_name='Grupos con Acceso'),
        ),
    ]
