"""
Django settings for intranet project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv

# Try to detect available LDAP backends/packages. We prefer django-auth-ldap if
# installed (it requires python-ldap), otherwise fall back to django-python3-ldap
# which uses ldap3 (pure Python).
ldap = None
LDAPSearch = None
HAS_DJANGO_AUTH_LDAP = False
HAS_DJANGO_PYTHON3_LDAP = False
try:
    # django-auth-ldap path
    import ldap as _ldap  # python-ldap
    from django_auth_ldap.config import LDAPSearch as _LDAPSearch
    ldap = _ldap
    LDAPSearch = _LDAPSearch
    HAS_DJANGO_AUTH_LDAP = True
except Exception:
    # django-auth-ldap not available or python-ldap missing
    ldap = None
    LDAPSearch = None
    HAS_DJANGO_AUTH_LDAP = False

try:
    import django_python3_ldap  # type: ignore
    HAS_DJANGO_PYTHON3_LDAP = True
except Exception:
    HAS_DJANGO_PYTHON3_LDAP = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project's .env located at BASE_DIR
# Prefer an explicit .env in the backend folder so variables are found even
# if the process is started from a different working directory.
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)
else:
    # Fallback to any .env found on the filesystem (optional)
    load_dotenv(find_dotenv())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-!4oml$f5j1_0x%^fjfv=+tbjk6phtb@xd-46$opg!ntw9=--(%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'api',
]

# Add django_python3_ldap if available
if HAS_DJANGO_PYTHON3_LDAP:
    INSTALLED_APPS.append('django_python3_ldap')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intranet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intranet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for Next.js integration
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000'
).split(',')

CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# -----------------------------
# Active Directory / LDAP
# -----------------------------
# The values below are read from environment variables so you can keep
# credentials out of source control. Fill them in in your environment
# or in a secure secrets manager before deploying.

# Example env vars used:
# AUTH_LDAP_SERVER_URI=ldap://ad.example.com
# AUTH_LDAP_BIND_DN=CN=binduser,OU=Users,DC=example,DC=com
# AUTH_LDAP_BIND_PASSWORD=supersecret
# AUTH_LDAP_USER_SEARCH_BASE=DC=example,DC=com
# AUTH_LDAP_USER_SEARCH_FILTER=(sAMAccountName=%(user)s)

AUTH_LDAP_SERVER_URI = os.environ.get('AUTH_LDAP_SERVER_URI', '')
AUTH_LDAP_BIND_DN = os.environ.get('AUTH_LDAP_BIND_DN', '')
AUTH_LDAP_BIND_PASSWORD = os.environ.get('AUTH_LDAP_BIND_PASSWORD', '')

# Configure depending on which LDAP integration package is installed.
if HAS_DJANGO_AUTH_LDAP and LDAPSearch is not None and ldap is not None:
    # django-auth-ldap configuration
    AUTH_LDAP_SERVER_URI = os.environ.get('AUTH_LDAP_SERVER_URI', AUTH_LDAP_SERVER_URI)
    AUTH_LDAP_BIND_DN = os.environ.get('AUTH_LDAP_BIND_DN', AUTH_LDAP_BIND_DN)
    AUTH_LDAP_BIND_PASSWORD = os.environ.get('AUTH_LDAP_BIND_PASSWORD', AUTH_LDAP_BIND_PASSWORD)

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        os.environ.get('AUTH_LDAP_USER_SEARCH_BASE', ''),
        ldap.SCOPE_SUBTREE,
        os.environ.get('AUTH_LDAP_USER_SEARCH_FILTER', '(sAMAccountName=%(user)s)')
    )

    AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": os.environ.get('AUTH_LDAP_ATTR_FIRST_NAME', 'givenName'),
        "last_name": os.environ.get('AUTH_LDAP_ATTR_LAST_NAME', 'sn'),
        "email": os.environ.get('AUTH_LDAP_ATTR_EMAIL', 'mail'),
    }

    AUTH_LDAP_ALWAYS_UPDATE_USER = True

    AUTHENTICATION_BACKENDS = [
        'django_auth_ldap.backend.LDAPBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]

elif HAS_DJANGO_PYTHON3_LDAP and AUTH_LDAP_SERVER_URI:
    # django-python3-ldap configuration (works with ldap3, pure Python)
    # See: https://github.com/etianen/django-python3-ldap
    # Only enable LDAP authentication if server URI is configured
    LDAP_AUTH_URL = AUTH_LDAP_SERVER_URI
    LDAP_AUTH_USE_TLS = os.environ.get('AUTH_LDAP_START_TLS', 'false').lower() in ('1', 'true', 'yes')
    LDAP_AUTH_CONNECTION_USERNAME = AUTH_LDAP_BIND_DN
    LDAP_AUTH_CONNECTION_PASSWORD = AUTH_LDAP_BIND_PASSWORD
    LDAP_AUTH_SEARCH_BASE = os.environ.get('AUTH_LDAP_USER_SEARCH_BASE', '')
    LDAP_AUTH_OBJECT_CLASS = os.environ.get('AUTH_LDAP_OBJECT_CLASS', 'person')

    # Map Django user fields to LDAP attributes
    LDAP_AUTH_USER_FIELDS = {
        'username': os.environ.get('AUTH_LDAP_ATTR_USERNAME', 'sAMAccountName'),
        'first_name': os.environ.get('AUTH_LDAP_ATTR_FIRST_NAME', 'givenName'),
        'last_name': os.environ.get('AUTH_LDAP_ATTR_LAST_NAME', 'sn'),
        'email': os.environ.get('AUTH_LDAP_ATTR_EMAIL', 'mail'),
    }
    
    # Sync AD groups to Django groups
    LDAP_AUTH_SYNC_USER_RELATIONS = 'api.ldap_sync.sync_user_relations'
    LDAP_AUTH_CLEAN_USER_DATA = 'api.ldap_sync.clean_user_data'
    
    # Format LDAP groups (memberOf attribute)
    LDAP_AUTH_FORMAT_SEARCH_FILTERS = 'api.ldap_sync.format_search_filters'
    LDAP_AUTH_FORMAT_USERNAME = 'django_python3_ldap.utils.format_username_openldap'

    # Authentication backend provided by django-python3-ldap
    AUTHENTICATION_BACKENDS = [
        'django_python3_ldap.auth.LDAPBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]

else:
    # No LDAP backend installed — fall back to default ModelBackend only
    AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
    ]

# Helpful flag: if you want to mirror LDAP groups into Django groups
# AUTH_LDAP_MIRROR_GROUPS = True

# Notes:
# - Install `django-auth-ldap` and its dependencies (python-ldap) or use an
#   alternative backend (ldap3) depending on your platform.
# - Keep binder credentials secret and use a service account with read-only
#   permissions on your directory.

