"""
Django settings for intranet project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv

# Import LDAP modules for django-auth-ldap
try:
    import ldap
    from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
    HAS_DJANGO_AUTH_LDAP = True
except ImportError:
    ldap = None
    LDAPSearch = None
    GroupOfNamesType = None
    HAS_DJANGO_AUTH_LDAP = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project's .env located at BASE_DIR
# Prefer an explicit .env in the backend folder so variables are found even
# if the process is started from a different working directory.
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)
else:
    # Fallback to any .env found on the filesystem (optional)
    load_dotenv(find_dotenv())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-!4oml$f5j1_0x%^fjfv=+tbjk6phtb@xd-46$opg!ntw9=--(%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intranet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intranet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for Next.js integration
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000'
).split(',')

CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# -----------------------------
# Active Directory / LDAP Configuration
# -----------------------------
# Simple django-auth-ldap configuration for Active Directory authentication

# Read LDAP settings from environment variables
AUTH_LDAP_SERVER_URI = os.environ.get('AUTH_LDAP_SERVER_URI', '')
AUTH_LDAP_BIND_DN = os.environ.get('AUTH_LDAP_BIND_DN', '')
AUTH_LDAP_BIND_PASSWORD = os.environ.get('AUTH_LDAP_BIND_PASSWORD', '')

# Configure django-auth-ldap if available and server URI is set
if HAS_DJANGO_AUTH_LDAP and AUTH_LDAP_SERVER_URI:
    # LDAP Server Settings
    AUTH_LDAP_SERVER_URI = AUTH_LDAP_SERVER_URI
    AUTH_LDAP_BIND_DN = AUTH_LDAP_BIND_DN
    AUTH_LDAP_BIND_PASSWORD = AUTH_LDAP_BIND_PASSWORD
    
    # Connection options to fix "Strong(er) authentication required" error
    # and support both LDAP and LDAPS connections
    # Network timeout: configurable via env var, default 5 seconds for faster fallback
    # when LDAP server is unreachable. Increase if you have slow network.
    ldap_timeout = int(os.environ.get('AUTH_LDAP_NETWORK_TIMEOUT', '5'))
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_NEVER,  # For self-signed certs
        ldap.OPT_REFERRALS: 0,  # Disable referrals (recommended for AD)
        ldap.OPT_NETWORK_TIMEOUT: ldap_timeout,  # Connection timeout in seconds
    }
    
    # For LDAPS (ldaps://), set global TLS options
    # This is required for SSL/TLS connections to work properly
    if AUTH_LDAP_SERVER_URI.startswith('ldaps://'):
        # Set global TLS options for LDAPS
        ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
        # For production with valid certificates, use:
        # ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_DEMAND)
        # ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, '/path/to/ca-cert.pem')
    
    # Enable START_TLS for plain LDAP connections (ldap://)
    # This encrypts the connection and satisfies AD's "strong authentication" requirement
    if AUTH_LDAP_SERVER_URI.startswith('ldap://'):
        AUTH_LDAP_START_TLS = True
    
    # User Search
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        os.environ.get('AUTH_LDAP_USER_SEARCH_BASE', 'DC=example,DC=com'),
        ldap.SCOPE_SUBTREE,
        os.environ.get('AUTH_LDAP_USER_SEARCH_FILTER', '(sAMAccountName=%(user)s)')
    )
    
    # Map LDAP attributes to Django user fields
    AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
    }
    
    # Group Search (optional but useful for role-based access)
    from django_auth_ldap.config import LDAPGroupQuery
    
    # Search for groups
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        os.environ.get('AUTH_LDAP_USER_SEARCH_BASE', 'DC=example,DC=com'),
        ldap.SCOPE_SUBTREE,
        "(objectClass=group)"
    )
    
    # Use group membership from Active Directory
    AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")
    
    # Map AD groups to Django groups and permissions
    AUTH_LDAP_FIND_GROUP_PERMS = True
    AUTH_LDAP_MIRROR_GROUPS = True
    
    # Update user profile on every login
    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    
    # Authentication backends
    AUTHENTICATION_BACKENDS = [
        'django_auth_ldap.backend.LDAPBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]
else:
    # No LDAP configured - use default Django authentication
    AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
    ]

